version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Prepare secrets
          command: |
            echo "DB_VPN_URL = \"0.0.0.0:0000\"" > ewapi/utils/database_secrets.py
            echo "DB_NAME = \"eW4\"" >> ewapi/utils/database_secrets.py
            echo "DB_LOGIN = \"not_relevant\"" >> ewapi/utils/database_secrets.py
            echo "DB_PASSWORD = \"eW4\"" >> ewapi/utils/database_secrets.py
      - run:
          name: Run tests
          command: python -m pytest tests
      - run:
          name: Build package
          command: python -m build
      - run:
          name: Push to Artifatory
          command: |
            cd dist
            ../jfrog config add ew4-pypi --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
            ../jfrog rt u "*" ew4-pypi --build-name=Build --build-number=$CIRCLE_BUILD_NUM --flat=false
workflows:
  main:
    jobs:
      - build-and-test
