version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: postgres
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Run tests
          command: python -m unittest tests/test_hello_world.py
      - run:
          name: Make package
          command: python -m build
      - run:
          name: Push to Artifatory
          command: |
            cd dist
            ../jfrog config add ew4-pypi --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
            ../jfrog rt u "*" ew4-pypi --build-name=Build --build-number=$CIRCLE_BUILD_NUM --flat=false
workflows:
  sample:
    jobs:
      - build-and-test
